/**
 * cafes.js — Static cafe dataset for Cihangir, Istanbul.
 *
 * Data sourced from OpenStreetMap / Google Maps Street View.
 * Format matches the internal cafe object used by Sunside:
 *   displayName.text  — cafe name
 *   location          — { latitude, longitude }
 *   outdoorSeating    — true | false | undefined
 *   rating            — 0–5 (community rating estimate)
 *   formattedAddress  — human-readable address
 *   facingDegrees     — compass direction the outdoor seating faces (0=N, 90=E, 180=S, 270=W)
 *   buildingFloors    — nearby building height in floors (used for shadow calculation)
 *   tolerance         — seating arc width in degrees (80–120)
 */

export const ISTANBUL_CAFES = [
  {
    id: "cafe-kronotrop",
    displayName: { text: "Kronotrop" },
    location: { latitude: 41.0338, longitude: 28.9779 },
    outdoorSeating: true,
    rating: 4.7,
    formattedAddress: "Turnacıbaşı Sk. No:6, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 4,
    tolerance: 90,
  },
  {
    id: "cafe-karabatak",
    displayName: { text: "Karabatak" },
    location: { latitude: 41.0337, longitude: 28.9793 },
    outdoorSeating: true,
    rating: 4.6,
    formattedAddress: "Kılıçali Paşa Mh., Cihangir Cd. No:7, Beyoğlu, İstanbul",
    facingDegrees: 225,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-forno",
    displayName: { text: "Forno" },
    location: { latitude: 41.0342, longitude: 28.9791 },
    outdoorSeating: true,
    rating: 4.5,
    formattedAddress: "Akarsu Yk. Cd. No:15, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 90,
    buildingFloors: 3,
    tolerance: 80,
  },
  {
    id: "cafe-petra",
    displayName: { text: "Petra Coffee" },
    location: { latitude: 41.0334, longitude: 28.9803 },
    outdoorSeating: true,
    rating: 4.5,
    formattedAddress: "Hayriye Cd. No:2A, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 4,
    tolerance: 90,
  },
  {
    id: "cafe-mandabatmaz",
    displayName: { text: "Mandabatmaz" },
    location: { latitude: 41.0333, longitude: 28.9773 },
    outdoorSeating: false,
    rating: 4.6,
    formattedAddress: "Olivia Geçidi No:1, Beyoğlu, İstanbul",
    facingDegrees: 270,
    buildingFloors: 5,
    tolerance: 80,
  },
  {
    id: "cafe-paper",
    displayName: { text: "Paper" },
    location: { latitude: 41.0323, longitude: 28.9798 },
    outdoorSeating: true,
    rating: 4.4,
    formattedAddress: "Ağa Hamamı Cd. No:1, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-coffeelab",
    displayName: { text: "Coffee Lab" },
    location: { latitude: 41.0329, longitude: 28.9785 },
    outdoorSeating: true,
    rating: 4.5,
    formattedAddress: "Sıraselviler Cd. No:29, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 135,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-baylan",
    displayName: { text: "Baylan Pastanesi" },
    location: { latitude: 41.0344, longitude: 28.9797 },
    outdoorSeating: true,
    rating: 4.3,
    formattedAddress: "Kumbaracı Yk. Cd. No:19, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 4,
    tolerance: 90,
  },
  {
    id: "cafe-geyik",
    displayName: { text: "Geyik Coffee" },
    location: { latitude: 41.0330, longitude: 28.9810 },
    outdoorSeating: true,
    rating: 4.4,
    formattedAddress: "Ağa Hamamı Cd. No:9, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 225,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-blackdot",
    displayName: { text: "Black Dot Coffee" },
    location: { latitude: 41.0326, longitude: 28.9788 },
    outdoorSeating: true,
    rating: 4.4,
    formattedAddress: "Sıraselviler Cd. No:7, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 4,
    tolerance: 90,
  },
  {
    id: "cafe-pita",
    displayName: { text: "Pita" },
    location: { latitude: 41.0346, longitude: 28.9784 },
    outdoorSeating: true,
    rating: 4.3,
    formattedAddress: "Akarsu Yk. Cd. No:8, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 225,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-urban",
    displayName: { text: "Urban Coffee" },
    location: { latitude: 41.0320, longitude: 28.9792 },
    outdoorSeating: true,
    rating: 4.2,
    formattedAddress: "Sıraselviler Cd. No:44, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 4,
    tolerance: 90,
  },
  {
    id: "cafe-privato",
    displayName: { text: "Cafe Privato" },
    location: { latitude: 41.0315, longitude: 28.9800 },
    outdoorSeating: true,
    rating: 4.3,
    formattedAddress: "Boğazkesen Cd. No:50, Tophane, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-smyrna",
    displayName: { text: "Smyrna" },
    location: { latitude: 41.0340, longitude: 28.9808 },
    outdoorSeating: true,
    rating: 4.2,
    formattedAddress: "Akarsu Aşağı Cd. No:27, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 135,
    buildingFloors: 4,
    tolerance: 90,
  },
  {
    id: "cafe-bumerang",
    displayName: { text: "Bumerang Kafe" },
    location: { latitude: 41.0348, longitude: 28.9800 },
    outdoorSeating: true,
    rating: 4.1,
    formattedAddress: "Kumbaracı Yk. Cd. No:42, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 270,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-freud",
    displayName: { text: "Freud Cafe" },
    location: { latitude: 41.0355, longitude: 28.9812 },
    outdoorSeating: true,
    rating: 4.2,
    formattedAddress: "Çukurcuma Cd. No:14, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 3,
    tolerance: 100,
  },
  {
    id: "cafe-kafe6",
    displayName: { text: "Kafe 6" },
    location: { latitude: 41.0358, longitude: 28.9820 },
    outdoorSeating: true,
    rating: 4.0,
    formattedAddress: "Çukurcuma Cd. No:6, Beyoğlu, İstanbul",
    facingDegrees: 90,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-moleskine",
    displayName: { text: "Moleskine Cafe" },
    location: { latitude: 41.0318, longitude: 28.9780 },
    outdoorSeating: false,
    rating: 4.3,
    formattedAddress: "Defterdar Yk. Cd. No:1, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 270,
    buildingFloors: 4,
    tolerance: 80,
  },
  {
    id: "cafe-havane",
    displayName: { text: "Havane" },
    location: { latitude: 41.0325, longitude: 28.9815 },
    outdoorSeating: true,
    rating: 4.1,
    formattedAddress: "Akarsu Aşağı Cd. No:5, Cihangir, Beyoğlu, İstanbul",
    facingDegrees: 225,
    buildingFloors: 3,
    tolerance: 90,
  },
  {
    id: "cafe-cihangir",
    displayName: { text: "Cihangir Kahvesi" },
    location: { latitude: 41.0350, longitude: 28.9790 },
    outdoorSeating: true,
    rating: 4.0,
    formattedAddress: "Cihangir Cd. No:22, Beyoğlu, İstanbul",
    facingDegrees: 180,
    buildingFloors: 4,
    tolerance: 100,
  },
];
