/**
 * libraries.js — Istanbul public libraries in GeoJSON format.
 * coordinates: [longitude, latitude]  (GeoJSON standard)
 * properties.facingDegrees — direction the reading garden/terrace faces
 * properties.hasOutdoorSeating — true if the library has an outdoor reading area
 */
export default {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9862, 41.0370] },
      properties: {
        name: "Atatürk Kitaplığı",
        area: "Beyoglu",
        address: "Mete Caddesi No:1, Taksim",
        hasOutdoorSeating: true,
        facingDegrees: 180,
        buildingFloors: 3,
        tolerance: 100,
        openingHours: "Mo-Fr 09:00-20:00, Sa 10:00-18:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9770, 41.0336] },
      properties: {
        name: "Beyoğlu İlçe Halk Kütüphanesi",
        area: "Beyoglu",
        address: "Yüksekkaldrım Cd. No:49, Beyoğlu",
        hasOutdoorSeating: false,
        facingDegrees: 90,
        buildingFloors: 4,
        tolerance: 90,
        openingHours: "Mo-Fr 09:00-18:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9834, 41.0316] },
      properties: {
        name: "Cihangir Kütüphanesi",
        area: "Cihangir",
        address: "Sıraselviler Cd. No:55, Cihangir",
        hasOutdoorSeating: true,
        facingDegrees: 180,
        buildingFloors: 3,
        tolerance: 90,
        openingHours: "Mo-Sa 09:00-19:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9740, 41.0282] },
      properties: {
        name: "Galata Kütüphanesi",
        area: "Galata",
        address: "Galata Kulesi Sk. No:2, Galata",
        hasOutdoorSeating: true,
        facingDegrees: 270,
        buildingFloors: 4,
        tolerance: 90,
        openingHours: "Mo-Su 09:00-21:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9682, 41.0243] },
      properties: {
        name: "Karaköy Kütüphanesi",
        area: "Karakoy",
        address: "Kemankeş Cd. No:18, Karaköy",
        hasOutdoorSeating: true,
        facingDegrees: 180,
        buildingFloors: 3,
        tolerance: 100,
        openingHours: "Mo-Fr 09:00-19:00, Sa 10:00-17:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9870, 41.0608] },
      properties: {
        name: "Şişli İlçe Halk Kütüphanesi",
        area: "Nisantasi",
        address: "Halaskargazi Cd. No:98, Şişli",
        hasOutdoorSeating: false,
        facingDegrees: 180,
        buildingFloors: 4,
        tolerance: 90,
        openingHours: "Mo-Fr 09:00-18:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [29.0092, 41.0442] },
      properties: {
        name: "Beşiktaş İlçe Halk Kütüphanesi",
        area: "Besiktas",
        address: "Barbaros Blv. No:24, Beşiktaş",
        hasOutdoorSeating: true,
        facingDegrees: 90,
        buildingFloors: 3,
        tolerance: 90,
        openingHours: "Mo-Fr 09:00-18:00, Sa 10:00-16:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [29.0485, 41.0760] },
      properties: {
        name: "Bebek Kütüphanesi",
        area: "Bebek",
        address: "Cevdet Paşa Cd. No:11, Bebek",
        hasOutdoorSeating: true,
        facingDegrees: 90,
        buildingFloors: 2,
        tolerance: 120,
        openingHours: "Mo-Sa 09:00-20:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9390, 41.0185] },
      properties: {
        name: "Fatih İlçe Halk Kütüphanesi",
        area: "Sultanahmet",
        address: "Fevzi Paşa Cd. No:72, Fatih",
        hasOutdoorSeating: false,
        facingDegrees: 180,
        buildingFloors: 3,
        tolerance: 90,
        openingHours: "Mo-Fr 09:00-18:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9526, 41.0340] },
      properties: {
        name: "Balat Kütüphanesi",
        area: "Balat",
        address: "Vodina Cd. No:33, Balat",
        hasOutdoorSeating: true,
        facingDegrees: 135,
        buildingFloors: 3,
        tolerance: 90,
        openingHours: "Mo-Sa 09:00-19:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9600, 41.0155] },
      properties: {
        name: "Eminönü İlçe Halk Kütüphanesi",
        area: "Eminonu",
        address: "Rüstem Paşa Mh., Eminönü",
        hasOutdoorSeating: false,
        facingDegrees: 180,
        buildingFloors: 4,
        tolerance: 90,
        openingHours: "Mo-Fr 09:00-18:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [29.0278, 41.0469] },
      properties: {
        name: "Ortaköy Kütüphanesi",
        area: "Ortakoy",
        address: "Muallim Naci Cd. No:5, Ortaköy",
        hasOutdoorSeating: true,
        facingDegrees: 90,
        buildingFloors: 2,
        tolerance: 120,
        openingHours: "Mo-Su 10:00-20:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [29.0178, 41.0282] },
      properties: {
        name: "Arnavutköy Kütüphanesi",
        area: "Arnavutkoy",
        address: "Salhane Sk. No:4, Arnavutköy",
        hasOutdoorSeating: true,
        facingDegrees: 90,
        buildingFloors: 2,
        tolerance: 110,
        openingHours: "Mo-Sa 09:00-19:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9840, 41.0255] },
      properties: {
        name: "İBB Tophane Kütüphanesi",
        area: "Karakoy",
        address: "Tophane İskele Cd., Tophane",
        hasOutdoorSeating: true,
        facingDegrees: 90,
        buildingFloors: 2,
        tolerance: 120,
        openingHours: "Mo-Su 09:00-22:00",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [28.9780, 41.0615] },
      properties: {
        name: "Nişantaşı Kütüphanesi",
        area: "Nisantasi",
        address: "Teşvikiye Cd. No:33, Nişantaşı",
        hasOutdoorSeating: true,
        facingDegrees: 180,
        buildingFloors: 3,
        tolerance: 90,
        openingHours: "Mo-Sa 09:00-20:00",
      },
    },
  ],
};
